### PR TITLE
CLI: Adding new command 'configuration' 

### LINKED ISSUE #711: CLI: add a `schema` command which prints schema
`openfn schema <adaptor>`

For an adaptor (with optional version), print the schema and sample configuration.

Maybe take `--schema` or `--sample` arguments to only print that one thing

This would enable us to maybe remove the Config section of the docs site

### PR DESCRIPTION
**Pull request by SatyamMattoo**
## Short Description

Added a new configuration command that retrieves and displays the configuration of a specified adaptor. The command supports flags to return the sample schema, full schema, or both.

## Related issue

Fixes #711 

## Implementation Details

Added a new configuration command to fetch and display adaptor configurations.
The command accepts an adaptor name (with or without a version) and retrieves the full configuration from the CDN.
Constructs a sample configuration using required fields and their examples from the full schema.
Supports `--schema` , `--sample`  and `--both` (default) flags to specify the desired output.

Command: `openfn configuration @openfn/language-dhis2 -o tmp/output.json --schema`

## QA Notes

Unit tests added for the command options and the configuration handler function. Tested locally with various adaptors to ensure correctness.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added unit tests

### CODE REVIEW

**Comment by josephjclark** [comment]
Hi @SatyamMattoo, thank you for this but shouldn't you be spending your time on the DMP job writing service?

**Comment by SatyamMattoo** [comment]
Hello @josephjclark,
Yes sir, I have been working on that as well. While adding the describe adaptor service to the gen_job service, I figured out this solution. It took a day to work through, and I thought it would be quite helpful.

Best regards,

**Comment by josephjclark** [comment]
Hi @SatyamMattoo - please don't maintain this PR for the time being. It is not worth your time.

I will look at it when I have time and give you feedback so that we can merge it in.

**Comment by SatyamMattoo** [comment]
Hello @josephjclark, I was just updating the main branch for my fork. Moving forward, I’ll make sure to branch off the main and work on separate branches as needed.

**Comment by josephjclark** [comment]
@SatyamMattoo No need to apologise! You've done nothing wrong.

If you want to keep a fork of `kit` in sync with kit, then you'll need to branch this CLI feature into a new branch and then just preserve main. Otherwise, any other work you do from your fork will include this CLI feature, making it much harder to merge.

If you're planing on making more contributions I'd appreciate it if you messaged me first. I really don't have much capacity over the next few weeks and my priority is to work out how to merge your DMP branch. I just want to make sure you spend your time effectively.

**Comment by SatyamMattoo** [comment]
@josephjclark Sure, I’ll branch it off as suggested. For the DMP, if I can assist with anything related to the merge or the feature, I’d be happy to help. I have some free time and can focus on speeding up the process.

**Pull request closed without merging**
