### PR TITLE
Worker: Log improvements and WORKER_MAX_SOCKET_TIMEOUT_SECONDS

### PR DESCRIPTION
**Pull request by josephjclark**
Adds WORKER_MAX_SOCKET_TIMEOUT_SECONDS variable to  control socket timeouts.

A few other tiny logging tweaks here.

### CODE REVIEW

**Comment by josephjclark** [comment]
@taylordowns2000 The websocket timeout should be working on this branch Image should be built for 1.5.5

I don't have any automated or manual tests on the actual timeout. I know the value is being passed in to the Pheonix socket, I've just not verified it's _working_. It's a little tricky to setup a slow response in the mock - although it should be possible of course.

If you can test manually on the image I'm happy to release. I'll probably spend an hour on it in the morning and see if I can crack it quickly.

**Comment by josephjclark** [comment]
Oh bottoms, it's all failed :( Ok, I'll fix in the morning

**Comment by josephjclark** [comment]
Ok, should be sorted now :+1:

**Comment by josephjclark** [comment]
Test added so I'm happy that this is working as expected

**Review by taylordowns2000 — APPROVED** [review]

**Pull request merged**
