### PR TITLE
Compiler: allow function calls on lazy state

### LINKED ISSUE #684: Lazy state fails on function calls
This should work:
```
fn((state) => {
   state.callMeMaybe = () => {}
  return state
});

fn($.callMeMaybe())
fn((state) => {
   $.callMeMaybe()
)
```

But it does not - $ is undefined.

This is likely just a compiler issue. I think we should allow the usecase

### PR DESCRIPTION
**Pull request by doc-han**
## Short Description

Currently function calls on lazy-state do not work. 
eg. 
```js
fn((state) => {
   state.callMeMaybe = () => {}
  return state
});
// does not work before this PR
fn($.callMeMaybe())
```
This is because, we fail to wrap the state callback well. This update fixes that.
#### How it worked before and after
Given the source code `fn($.callMeMaybe())`
| Before this PR                             | After this PR                            |
|--------------------------------------------|------------------------------------------|
| ``` fn((state => state.callMeMaybe)()) ``` | ``` fn(state => state.callMeMaybe()) ``` |

Fixes #684 

#### Steps
1. after finding the MemberExpression with $, we start walking up the tree to find a CallExpression to wrap. 
2. when we find this CallExpression, a simple check is done to find out whether the parent of this CallExpression is another CallExpression with callee being state. (that's how we know it's a function called on a lazy-state)
3. we then want to wrap the state stuff at an additional level up for it to work!

## QA Notes

List any considerations/cases/advice for testing/QA here.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### CODE REVIEW

**Comment by doc-han** [comment]
@josephjclark I want to add a good runtime/cli test for this. where do you think would be best to add that. 
```js
fn((state) => {
    state.callMeMaybe = (value) => {
        state.greetings = `hello ${value}`
		return state; // crazy! seems every function body that does something with state has to return it
    }
    return state
});

fn(state => {
    state.name = "John"
    return state;
})

fn($.callMeMaybe($.name)) // note: if callMeMaybe doesn't return state, next operation wouldn't have state passed.

```
Then the value at `state.greetings` will be `"hello John"`


### Note
We can say that. every function body that has something to do with state should return it.

**Comment by josephjclark** [comment]
> every function body that has something to do with state should return it.

Uh, well not really. It depends on how it's used. We talk about Operations - a function which takes state and returns state. If you're using a function as an _operation_ - then yeah, the function body must return state.

But I can re-write your code like this:
```
fn((state) => {
    state.callMeMaybe = (value) => {
        state.greetings = `hello ${value}`
    }
    return state
});

fn(state => {
    state.callMeMaybe(); // no need to return state in this case
    return state;
})
```

But I think you're hitting on something important. Since we can't use lazy state inside a callback, the use of this is limited.

If I do:
```
fn($.callMeMaybe($.name))
```
Then the function must indeed be an Operation.

We can do stuff like this though
```
fn((state) => {
  state.buildUrl = (resource) => `api/v1/${resource}`
  return state;
});
get($.buildUrl(resourceName))
```

But thinking this through is making me really de-value the utility of functions on state. I think it's just creating confusion.

 #648 would be a much more useful facility (although the issue needs a lot of love!)

**Comment by josephjclark** [comment]
@doc-han let me think about this but this does feel low priority now :thinking:  If it feels safe I'll merge it

**Comment by josephjclark** [comment]
Hiya @doc-han - I want to merge this even though I don't think it's very valuable in the end.


We have a suite of tests in `integration-tests/execute` which test the compiler and runtime on job code. This is quite new and we don't have many - but it's nice to be able to test job code without the overhead of the CLI (or indeed the multi-process worker engine).

Can I ask you to create a file called `lazy-state.test.ts` in there and add a few simple lazy state tests and then a test or two on this specifically?

Don't go too overboard - just plug in a nice starting point :)

Thanks!

**Comment by doc-han** [comment]
> Can I ask you to create a file called `lazy-state.test.ts` in there and add a few simple lazy state tests and then a test or two on this specifically?

Done

**Review by josephjclark — APPROVED** [review]

**Comment by josephjclark** [comment]
Thanks @doc-han ! Appreciate it

**Pull request merged**
