### PR TITLE
Logger: Sensitive logging

### LINKED ISSUE #211: CLI: [object Object] in logs
This sort of thing can creep up all over the place, but there's at least one reproducible (I think) example of an uphelpful [object Object] creeping into the logs:
```
[R/T] ✘ Error in runtime execution!
[R/T] ✘ [object Object]
[CLI] ✘ Error: runtime exception
[CLI] ✘ Took 3.77s.
```
The double error at the end there is a bit of a smell too - the CLI and runtime both sort of duplicate the report.

I think this issue is caused by dhis2 reject a request with no/invalid credentials.

Full repro log:

```
➜  cli-tutorial openfn hello.js -ia dhis2 -l debug      
[CLI] ℹ Versions:
         ▸ node.js                   18.10.0
         ▸ cli                       0.0.35
         ▸ runtime                   0.0.21
         ▸ compiler                  0.0.29
         ▸ @openfn/language-dhis2    latest
[CLI] ℹ Auto-installing language adaptors
[CLI] ✔ Installing packages...
[CLI] ❯ repoDir is set to: /tmp/openfn/repo
[CLI] ℹ Looked up latest version of @openfn/language-dhis2: found 3.2.11
[CLI] ❯ Using latest installed version of @openfn/language-dhis2: 3.2.11
[CLI] ℹ Skipping @openfn/language-dhis2@3.2.11 as already installed
[CLI] ✔ Installation complete in 1.955s
[CLI] ❯ Load state...
[CLI] ℹ No state provided - using default state { data: {}, configuration: {}
[CLI] ❯ Loading job...
[CLI] ❯ Attempting to preload types for @openfn/language-dhis2
[CLI] ❯ Using latest installed version of @openfn/language-dhis2: 3.2.11
[CLI] ❯ Starting compilation
[CLI] ❯ Compiling from file at hello.js
[CLI] ❯ Parsed source tree
[CLI] ℹ Added import statement for @openfn/language-dhis2
[CLI] ℹ Added export * statement for @openfn/language-dhis2
[CLI] ❯ Transformed source AST
[CLI] ❯ Compiled source:
[CLI] ❯ import { upsert } from "@openfn/language-dhis2";
export * from "@openfn/language-dhis2";

export default [upsert("dataValue", {
    orgUnit: "ImspTQPwCqd",
    dataSet: "QX4ZTUbOt3a",
    country: "PT59n8BQbqM",
    period: "202303",
    value: 14
})];
[CLI] ✔ Compiled job from hello.js
[R/T] ❯ Intialising pipeline
[R/T] ❯ Timeout set to 300000ms
[R/T] ❯ [linker] loading module @openfn/language-dhis2
[R/T] ❯ Using latest installed version of @openfn/language-dhis2: 3.2.11
[R/T] ❯ [linker] Loading module @openfn/language-dhis2 from /tmp/openfn/repo/node_modules/@openfn/language-dhis2_3.2.11/dist/index.cjs
[R/T] ℹ Resolved adaptor @openfn/language-dhis2 to version 3.2.11
[R/T] ❯ Executing pipeline (1 operations)
⚠ Warning at Tue Apr 11 2023 13:32:20 GMT+0300 (East Africa Time):
 DEPRECATION WARNING: Please migrate instance address from `apiUrl` to `hostUrl`.
[R/T] ❯ Starting operation 1
Preparing upsert via 'get' then 'create' OR 'update'...
Preparing get operation...
Using latest available version of the DHIS2 api on this server.
Sending get request to undefined/api/dataValue
 with params: {
  orgUnit: 'ImspTQPwCqd',
  dataSet: 'QX4ZTUbOt3a',
  country: 'PT59n8BQbqM',
  period: '202303',
  value: 14
}
✗ Error at Tue Apr 11 2023 13:32:20 GMT+0300 (East Africa Time):
 connect ECONNREFUSED ::1:80
[R/T] ✘ Error in runtime execution!
[R/T] ✘ [object Object]
[CLI] ✘ Error: runtime exception
[CLI] ✘ Took 3.77s.
```

### LINKED ISSUE #314: Logger: sensitive mode
Design for "sensitive logging" in the logger.

By "sensitive logging" I mean: don't log potentially sensitive state objects when running jobs with real data. I would like a better name.

strict logging? safe logging? private logging? production logging? stateless logging? text only logging? idk.

The idea is that when sensitive mode is enabled, the logger should automatically remove/obfuscate all objects (and arrays) that are sent to the console.

This is deliberately a crude and conservative filter: the logger will protect the user from logging sensitive/personally identifiable information by basically never logging objects.

Note that strings sent to the console (including JSON.stringify) will still be shown verbatim.

This is a flag on the logger itself, so it can be applied to CLI and RTM logging.

Advantages of this approach:
* Job writers can continue to use console.log to output whatever debug information they want
* When running against a real or sensitive data source, state will be safely ellided
* Jobs written for dev and debug are 100% safe to run in production.

Tasks:
* Add a sensitive/clean/stateless/ flag to the logger
* Add a `--log-sensitive` flag to the CLI
* The CLI should report when sensitive mode is enabled (and maybe why). In Lightning we may want to show a clearer message outside of the log.
* Elegantly and helpfully ellide the object.
* * [Object]
* * "Object with keys: x, y, z
* * "Array of 122 objects (with keys a,b,c)" (based on the first object? Superset of all?)
* Note that logger.print (and logger.always?) should ignore this flag

Possible issues:
* This will apply to adaptor code too - this is probably a good thing, but will anything break?
* We should continue to serialize and log error objects

## Lightning Integration

How Lightning uses this flag is up to Lightning. I'll raise a ticket over there to cover the UX options.

## Related issues

This issue supercedes #182 #276. It will probably fix #211 (if it's not already fixed)

### PR DESCRIPTION
**Pull request by josephjclark**
## Short Description

This PR adds options to "sanitise" output in the logger.

Which basically means: if someone tries to log state in a production environment, the logger should automatically remove or obfuscate it.

This PR adds three options: obfuscate, summarize, or remove. By default it will not attempt to sanitize objects (except for state, where we ALWAYS sanitize config), because the CLI is primarily developer tooling.

See the comment below for examples.

## Related issue

Fixes #314 (and I think #211  can be closed out now too)

## Implementation Details

The logger itself takes a `sanitize` argument with different "policies" for what to do when an object or array is logged.

The CLI accepts this as an input and feeds it through to the logger.

If you try and pass an unknown sanitize value, the CLI will abort in very dramatic circumstances (before running any of the job pipeline). That's because if you want to sanitize your output and you make a typo in the argument, it would be irresponsible to run. You're basically telling us you're trying to run in a sensitive production environment where you don't want to log anything.  In practice, of course, this will never happen because those environments are automated. And if you mis-spell "sanitize" I can't help you. But still, one day this might help someone out.

Note that this doesn't yet affect lightning at all - lightning will need to pass an extra flag to the CLI.

## QA Notes

The best way to test this is to create a job which logs some complex values, and see how the logger handles it with different sanitize options.

First install the dev build of openfn, called `openfnx`. From root, do:

`pnpm install && pnpm install:openfx`

(this will build for you and install a global command called `openfnx`)

Then you'll need a test job to run. Here's a simple one:

```
// job.js
fn((s) => {
  console.log({});
  return s;
});
```

Then run this from the CLI. You probably want to do this from a temp directory lest you accidentally check in stuff to the repo@
```
openfnx job.js -ia common --sanitize=summarize
```
Look out for the `[JOB]` log line - that's the bit emitted by your job code, and the bit that should be sanitized.

You can drop the `-i` flag after you've run the job for the first time (it'll run a bit quicker then)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added unit tests
- [ ] Changesets have been added (if there are production code changes)

### CODE REVIEW

**Comment by josephjclark** [comment]
Example console output from dev builds (excluding version output)

## No sanitisation (default):
Note the three JOB outputs - an object and an array and a mixture

```
> pnpm openfn tmp/log.js -a common

[CLI] ✔ Compiled from tmp/log.js
[R/T] ♦ Starting job job-1
[JOB] ℹ {
  "a": 1,
  "b": 2
}
[JOB] ℹ obj {
  "a": 1,
  "b": 2
}
[JOB] ℹ [
  {
    "a": 1,
    "b": 2
  }
][R/T] ✔ Completed job job-1 in 207ms
[CLI] ✔ State written to tmp/output.json
[CLI] ✔ Finished in 317ms ✨
```

## Obfuscation

This mode will do a simple flat obfuscation of any objects and arrays (this is dumb by  design!)

```
> pnpm openfn tmp/log.js -a common --sanitize=obfuscate

[CLI] ✔ Compiled from tmp/log.js
[R/T] ♦ Starting job job-1
[JOB] ℹ [object]
[JOB] ℹ obj [object]
[JOB] ℹ [array]
[R/T] ✔ Completed job job-1 in 203ms
[CLI] ✔ State written to tmp/output.json
[CLI] ✔ Finished in 308ms ✨
```
## Summarize

This mode will summarize arrays and objects. This should prevent anything sensitive being printed, but could still show useful debug output.

```
> pnpm openfn tmp/log.js -a common --sanitize=summarize

[CLI] ✔ Compiled from tmp/log.js
[R/T] ♦ Starting job job-1
[JOB] ℹ (object with keys a, b)
[JOB] ℹ obj (object with keys a, b)
[JOB] ℹ (array with 1 items)
[R/T] ✔ Completed job job-1 in 214ms
[CLI] ✔ State written to tmp/output.json
[CLI] ✔ Finished in 318ms ✨
```

## Remove

This will entirely remove lines with objects and arrays, or log null if an object was in a line (maybe this is too confusing?)
 ```
> pnpm openfn tmp/log.js -a common --sanitize=remove

[CLI] ✔ Compiled from tmp/log.js
[R/T] ♦ Starting job job-1
[JOB] ℹ obj null
[R/T] ✔ Completed job job-1 in 248ms
[CLI] ✔ State written to tmp/output.json
[CLI] ✔ Finished in 346ms ✨
```

**Comment by josephjclark** [comment]
Breaking for the day but I think the last thing needed here is a couple of integration tests against the sanitize option. It's too important to not test really robustly!

**Review by taylordowns2000 — APPROVED** [review]
this rocks. thank you. tested and good to go

**Review by taylordowns2000 — APPROVED** [review]
this rocks. thank you. tested and good to go

**Pull request merged**
