### PR TITLE
Fix lazy state

### PR DESCRIPTION
**Pull request by josephjclark**
The lazy state operator `$` is causing trouble if you try to use `$` as a variable, a la:

```
parseXML(state.data, $ => {
    const inner = $.load(response.text()); // error
 });
```

This PR adds a bit of intelligence to the is-this-a-lazy-state-reference heuristic to ignore $ variable declared in the source. See the unit tests for details.

### CODE REVIEW

**Comment by josephjclark** [comment]
@mtuchi assuming this passes CI tests and it works for you, you can merge it and it'll be released! You'll have to ask Taylor to bump the lightning worker

**Comment by mtuchi** [comment]
@josephjclark let's hold this, i would love to test before merging.

**Comment by mtuchi** [comment]
Hiya @josephjclark i have tested this, it works as expected. Thanks for the fix 👍🏽

**Review by mtuchi — APPROVED** [review]
Tested locally on water-aid project, it works as expected 👍🏽

**Pull request merged**
